version: "3.8"
services:
  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  ai-service:
    build: ./ai-service
    image: ai-resume-analyzer:latest
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./ai-service:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1

  backend:
    build:
      context: ./backend
    image: ai-resume-backend:latest
    command: node src/server.js
    volumes:
      - ./backend:/usr/src/app
      - ./uploads:/usr/src/app/uploads
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/resume_db
      - JWT_SECRET=supersecretjwt
      - AI_SERVICE_URL=http://ai-service:8000
    depends_on:
      - mongo
      - ai-service

volumes:
  mongo-data:
